version = 0.1

[default]
[default.global]
[default.global.parameters]
template_file = "nyc-od-lambda.aws-sam.yaml"
stack_name = "nyc-od-lambda"

[default.validate.parameters]
lint = true

[default.package.parameters]
resolve_s3 = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
